from pysat.formula import CNF
from pysat.solvers import Solver
from pathlib import Path
from typing import List, Tuple
from domain.grammar_types import NonTerminal, Grammar
from modules.CYK import cyk_accepts
from modules.parser import parse_grammar_file_to_chomsky


class CFG_2_SAT():
    def __init__(self, grammar:Grammar, word:str, solve: bool = False, save_dimacs: bool = True, verbose: bool = True):
        self.grammar = grammar
        self.input_path = getattr(grammar, "source_path", None)
        self.dimacs_path = None
        self.save_dimacs_enabled = save_dimacs
        self.verbose = verbose

        self.word = word.strip()
        self.word_tokens = [] if self.word == "" else self.word.split()
        self.stats = {
            "nonterminal_count": len(self.grammar.NonTerminals),
            "rule_count": len(self.grammar.rules),
            "singular_rule_count": sum(1 for r in self.grammar.rules if r.type == "SINGULAR"),
            "double_rule_count": sum(1 for r in self.grammar.rules if r.type == "DOUBLE"),
            "word_length": len(self.word_tokens),
            "base_bool_variable_count": 0,
            "tseitin_variable_count": 0,
            "bool_variable_count": 0,
            "fixed_value_clause_count": 0,
            "tseitin_clause_count": 0,
            "window_clause_count": 0,
            "clause_count": 0,
        }

        if len(self.word_tokens) == 0:
            if getattr(grammar, "accepts_epsilon", False):
                if self.verbose:
                    print("formula is satisfiable, empty word ε is generated by the grammar")
                    print(f"- {self.grammar.startingSymbol.value} => ε")
            else:
                if self.verbose:
                    print("formula is unsatisfiable, empty word ε is not generated by the grammar")
            return

        self.bools = self.init_bools()
        self.stats["base_bool_variable_count"] = len(self.bools)
        self.clauses = self.init_clauses()
        self.stats["clause_count"] = len(self.clauses)
        if self.save_dimacs_enabled:
            self.dimacs_path = self.save_dimacs()
        if solve:
            self.solve_pysat()
        

    def init_bools(self) -> dict:
        '''
        Initialize a dictionarie of sets, where the keys are this form N,i,j, where i <= j <= len(word), and the values are (boolean_value, name).
        The first value will be used to store the boolean values of whether the nonterminal can generate the substring of the word from index i to index j,
        and the second value will be used to store the value name used in the SAT solver.
        '''
        bools = {}
        solver_name = 1
        n = len(self.word_tokens)

        for nonterminal in self.grammar.NonTerminals:
            for i in range(n):
                for j in range(i, n):
                    bools[nonterminal.value + ',' + str(i) + ',' + str(j)] = (None, solver_name)
                    solver_name += 1

        # set table[S,0,n-1] to true
        bools[self.grammar.startingSymbol.value + ',0,' + str(n - 1)] = (
            True,
            bools[self.grammar.startingSymbol.value + ',0,' + str(n - 1)][1]
        )

        # if exists a rule A -> a, then set table[A,i,i] to true if word_tokens[i] == a
        for rule in self.grammar.rules:
            if rule.type == 'SINGULAR':
                for i in range(n):
                    if self.word_tokens[i] == rule.terminal.value:
                        bools[rule.nonterminal.value + ',' + str(i) + ',' + str(i)] = (
                            True,
                            bools[rule.nonterminal.value + ',' + str(i) + ',' + str(i)][1]
                        )

        # set all other [i,i] values to false
        for nonterminal in self.grammar.NonTerminals:
            for i in range(n):
                if bools[nonterminal.value + ',' + str(i) + ',' + str(i)][0] is None:
                    bools[nonterminal.value + ',' + str(i) + ',' + str(i)] = (
                        False,
                        bools[nonterminal.value + ',' + str(i) + ',' + str(i)][1]
                    )

        # if for nonterminal A there is no rule A -> BC, then set all [A,i,j] with i<j to false
        for nonterminal in self.grammar.NonTerminals:
            has_double_rule = False
            for rule in self.grammar.rules:
                if rule.type == 'DOUBLE' and rule.nonterminal.value == nonterminal.value:
                    has_double_rule = True
                    break
            if not has_double_rule:
                for i in range(n):
                    for j in range(i + 1, n):
                        bools[nonterminal.value + ',' + str(i) + ',' + str(j)] = (
                            False,
                            bools[nonterminal.value + ',' + str(i) + ',' + str(j)][1]
                        )

        return bools
    
    def init_clauses(self) -> List[List[int]]:
        clauses = []
        fixed_value_clause_count = 0
        tseitin_clause_count = 0
        window_clause_count = 0
        tseitin_variable_count = 0

        # fixed truth values
        for key in self.bools:
            val, var = self.bools[key]
            if val is True:
                clauses.append([var])
                fixed_value_clause_count += 1
            elif val is False:
                clauses.append([-var])
                fixed_value_clause_count += 1

        n = len(self.word_tokens)

        # group DOUBLE rules by LHS
        rules_by_lhs = {}
        for r in self.grammar.rules:
            if r.type == "DOUBLE":
                rules_by_lhs.setdefault(r.nonterminal.value, []).append(r)

        # allocate new SAT variables for Tseitin auxiliaries
        next_var = max(v for (_, v) in self.bools.values()) + 1

        # helper to get var id quickly
        def V(sym, i, j):
            return self.bools[f"{sym},{i},{j}"][1]

        for A, rules_list in rules_by_lhs.items():
            for i in range(n):
                for j in range(i + 1, n):
                    Aij = V(A, i, j)

                    option_vars = []  # z vars for each (rule,k)

                    for rule in rules_list:
                        B = rule.nonterminal2.value
                        C = rule.nonterminal3.value

                        for k in range(i, j):
                            Bik = V(B, i, k)
                            Ckj = V(C, k + 1, j)

                            z = next_var
                            next_var += 1
                            option_vars.append(z)
                            tseitin_variable_count += 1

                            # z <-> (Bik & Ckj)
                            # z -> Bik and z -> Ckj
                            clauses.append([-z, Bik])
                            clauses.append([-z, Ckj])
                            # (Bik & Ckj) -> z
                            clauses.append([-Bik, -Ckj, z])
                            tseitin_clause_count += 3

                    # Aij -> OR(option_vars)
                    # (-Aij v z1 v z2 v ...)
                    if option_vars:
                        clauses.append([-Aij] + option_vars)
                    else:
                        # no way to derive length>=2 substring => force false
                        clauses.append([-Aij])
                    window_clause_count += 1

        self.stats["fixed_value_clause_count"] = fixed_value_clause_count
        self.stats["tseitin_clause_count"] = tseitin_clause_count
        self.stats["window_clause_count"] = window_clause_count
        self.stats["tseitin_variable_count"] = tseitin_variable_count
        self.stats["bool_variable_count"] = self.stats["base_bool_variable_count"] + tseitin_variable_count

        return clauses

    def get_stats(self) -> dict[str, int]:
        return dict(self.stats)
    
    def solve_pysat(self) -> None:
        cnf = CNF(from_clauses=self.clauses)

        with Solver(bootstrap_with=cnf) as solver:
            sat_result = solver.solve()
            cyk_result = cyk_accepts(self.grammar, self.word_tokens)

            if sat_result:
                print('formula is satisfiable, word : ' + self.word + ' is generated by the grammar')
                self.print_derivation(solver.get_model())
            else:
                print('formula is unsatisfiable, word : ' + self.word + ' is not generated by the grammar')

            if sat_result == cyk_result:
                print('CYK check: OK (SAT and CYK results match)')
            else:
                print('CYK check: MISMATCH (SAT=' + str(sat_result) + ', CYK=' + str(cyk_result) + ')')

    def _dimacs_output_path(self) -> Path:
        if self.input_path is None:
            input_path = Path("src/text/input/grammar.txt")
        else:
            input_path = Path(self.input_path)

        suffix = input_path.suffix if input_path.suffix else ".txt"
        output_dir = input_path.parent.parent / "dimacs_outputs"
        source_total = getattr(self.grammar, "source_total", 1)
        if source_total > 1:
            output_dir = output_dir / input_path.stem

        grammar_index = getattr(self.grammar, "source_index", None)
        if grammar_index is None:
            filename = input_path.stem + "_dimacs" + suffix
        else:
            filename = input_path.stem + f"_g{grammar_index + 1}_dimacs" + suffix
        return output_dir / filename

    def save_dimacs(self) -> str | None:
        if not self.clauses:
            return None

        num_variables = 0
        for clause in self.clauses:
            for literal in clause:
                num_variables = max(num_variables, abs(literal))

        output_path = self._dimacs_output_path()
        grammar_name = Path(self.input_path).name if self.input_path else "unknown"
        safe_word = self.word.replace("\n", " ").strip()

        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as dimacs_file:
            dimacs_file.write(f"c grammar={grammar_name} word={safe_word}\n")
            dimacs_file.write(
                "c stats "
                f"nonterminals={self.stats['nonterminal_count']} "
                f"rules={self.stats['rule_count']} "
                f"word_length={self.stats['word_length']} "
                f"bool_variables={self.stats['bool_variable_count']} "
                f"clauses={self.stats['clause_count']}\n"
            )
            dimacs_file.write(f"p cnf {num_variables} {len(self.clauses)}\n")
            for clause in self.clauses:
                dimacs_file.write(" ".join(str(literal) for literal in clause) + " 0\n")

        if self.verbose:
            print(f"DIMACS CNF saved to: {output_path}")
        return str(output_path)
    
    def print_derivation(self, model: list[int]) -> None:
        for key in self.bools:
            if self.bools[key][1] in model:
                self.bools[key] = (True, self.bools[key][1])
            else:
                self.bools[key] = (False, self.bools[key][1])

        def substring_tokens(i: int, j: int) -> str:
            return ' '.join(self.word_tokens[i:j+1])

        def print_derivation_helper(nonterminal: NonTerminal, i: int, j: int, indent: str):
            if i > j:
                return

            if self.bools[nonterminal.value + ',' + str(i) + ',' + str(j)][0] == False:
                return

            print(indent + nonterminal.value + ' generates ' + substring_tokens(i, j))

            for rule in self.grammar.rules:
                if (
                    rule.type == 'SINGULAR'
                    and rule.nonterminal.value == nonterminal.value
                    and i == j
                    and rule.terminal.value == self.word_tokens[i]
                ):
                    print(indent + '- ' + nonterminal.value + ' -> ' + rule.terminal.value)
                    return

                elif rule.type == 'DOUBLE' and rule.nonterminal.value == nonterminal.value:
                    for k in range(i, j):
                        left_key = rule.nonterminal2.value + ',' + str(i) + ',' + str(k)
                        right_key = rule.nonterminal3.value + ',' + str(k + 1) + ',' + str(j)

                        if self.bools[left_key][0] == True and self.bools[right_key][0] == True:
                            print(indent + '- ' + nonterminal.value + ' -> ' + rule.nonterminal2.value + ' ' + rule.nonterminal3.value)
                            print_derivation_helper(rule.nonterminal2, i, k, indent + '- ')
                            print_derivation_helper(rule.nonterminal3, k + 1, j, indent + '- ')
                            return

        print_derivation_helper(self.grammar.startingSymbol, 0, len(self.word_tokens) - 1, '- ')
