from pysat.formula import CNF
from pysat.solvers import Solver
from grammar_types import Terminal, NonTerminal, Rule, Grammar
from parser import parse_grammar_file_to_cnf

def print_grammar(grammar:Grammar):
    print("NonTerminals: " + str([nt.value for nt in grammar.NonTerminals]))
    print("Terminals: " + str([t.value for t in grammar.Terminals]))
    print("Starting Symbol: " + grammar.startingSymbol.value)
    print("Rules:")
    if getattr(grammar, "accepts_epsilon", False):
        print("- " + grammar.startingSymbol.value + " -> ε")
    for rule in grammar.rules:
        if rule.type == 'SINGULAR':
            print(f"- {rule.nonterminal.value} -> {rule.terminal.value}")
        else:
            print(f"- {rule.nonterminal.value} -> {rule.nonterminal2.value} {rule.nonterminal3.value}")

def generate_variants(lists):
    if not lists:
        return [[]]
    
    result = []
    first = lists[0]
    rest = generate_variants(lists[1:])
    
    for item in first:
        for combination in rest:
            result.append([item] + combination)
    
    return result


class CFG_2_SAT():
    def __init__(self, grammar:Grammar, word:str):
        self.rules = grammar.rules
        self.NonTerminals = grammar.NonTerminals
        self.Terminals = grammar.Terminals
        self.startingSymbol = grammar.startingSymbol

        self.word = word.strip()
        self.word_tokens = [] if self.word == "" else self.word.split()

        if len(self.word_tokens) == 0:
            if getattr(grammar, "accepts_epsilon", False):
                print("formula is satisfiable, empty word ε is generated by the grammar")
                print(f"- {self.startingSymbol.value} => ε")
            else:
                print("formula is unsatisfiable, empty word ε is not generated by the grammar")
            return

        self.bools = self.init_bools()
        self.clauses = self.init_clauses()
        self.solve()
        

    def init_bools(self):
        '''
        Initialize a dictionarie of sets, where the keys are this form N,i,j, where i <= j <= len(word), and the values are (boolean_value, name).
        The first value will be used to store the boolean values of whether the nonterminal can generate the substring of the word from index i to index j,
        and the second value will be used to store the value name used in the SAT solver.
        '''
        bools = {}
        solver_name = 1
        n = len(self.word_tokens)

        for nonterminal in self.NonTerminals:
            for i in range(n):
                for j in range(i, n):
                    bools[nonterminal.value + ',' + str(i) + ',' + str(j)] = (None, solver_name)
                    solver_name += 1

        # set table[S,0,n-1] to true
        bools[self.startingSymbol.value + ',0,' + str(n - 1)] = (
            True,
            bools[self.startingSymbol.value + ',0,' + str(n - 1)][1]
        )

        # if exists a rule A -> a, then set table[A,i,i] to true if word_tokens[i] == a
        for rule in self.rules:
            if rule.type == 'SINGULAR':
                for i in range(n):
                    if self.word_tokens[i] == rule.terminal.value:
                        bools[rule.nonterminal.value + ',' + str(i) + ',' + str(i)] = (
                            True,
                            bools[rule.nonterminal.value + ',' + str(i) + ',' + str(i)][1]
                        )

        # set all other [i,i] values to false
        for nonterminal in self.NonTerminals:
            for i in range(n):
                if bools[nonterminal.value + ',' + str(i) + ',' + str(i)][0] is None:
                    bools[nonterminal.value + ',' + str(i) + ',' + str(i)] = (
                        False,
                        bools[nonterminal.value + ',' + str(i) + ',' + str(i)][1]
                    )

        # if for nonterminal A there is no rule A -> BC, then set all [A,i,j] with i<j to false
        for nonterminal in self.NonTerminals:
            has_double_rule = False
            for rule in self.rules:
                if rule.type == 'DOUBLE' and rule.nonterminal.value == nonterminal.value:
                    has_double_rule = True
                    break
            if not has_double_rule:
                for i in range(n):
                    for j in range(i + 1, n):
                        bools[nonterminal.value + ',' + str(i) + ',' + str(j)] = (
                            False,
                            bools[nonterminal.value + ',' + str(i) + ',' + str(j)][1]
                        )

        return bools
    
    def init_clauses(self):
        clauses = []

        # fixed truth values
        for key in self.bools:
            val, var = self.bools[key]
            if val is True:
                clauses.append([var])
            elif val is False:
                clauses.append([-var])

        n = len(self.word_tokens)

        # group DOUBLE rules by LHS
        rules_by_lhs = {}
        for r in self.rules:
            if r.type == "DOUBLE":
                rules_by_lhs.setdefault(r.nonterminal.value, []).append(r)

        # allocate new SAT variables for Tseitin auxiliaries
        next_var = max(v for (_, v) in self.bools.values()) + 1

        # helper to get var id quickly
        def V(sym, i, j):
            return self.bools[f"{sym},{i},{j}"][1]

        for A, rules_list in rules_by_lhs.items():
            for i in range(n):
                for j in range(i + 1, n):
                    Aij = V(A, i, j)

                    option_vars = []  # z vars for each (rule,k)

                    for rule in rules_list:
                        B = rule.nonterminal2.value
                        C = rule.nonterminal3.value

                        for k in range(i, j):
                            Bik = V(B, i, k)
                            Ckj = V(C, k + 1, j)

                            z = next_var
                            next_var += 1
                            option_vars.append(z)

                            # z <-> (Bik & Ckj)
                            # z -> Bik and z -> Ckj
                            clauses.append([-z, Bik])
                            clauses.append([-z, Ckj])
                            # (Bik & Ckj) -> z
                            clauses.append([-Bik, -Ckj, z])

                    # Aij -> OR(option_vars)
                    # (-Aij v z1 v z2 v ...)
                    if option_vars:
                        clauses.append([-Aij] + option_vars)
                    else:
                        # no way to derive length>=2 substring => force false
                        clauses.append([-Aij])

        return clauses
    
    def solve(self):
        cnf = CNF(from_clauses=self.clauses)

        with Solver(bootstrap_with=cnf) as solver:
            if solver.solve():
                print('formula is satisfiable, word : ' + self.word + ' is generated by the grammar')
                self.print_derivation(solver.get_model())
            else:
                print('formula is unsatisfiable, word : ' + self.word + ' is not generated by the grammar')
    
    def print_derivation(self, model: list[int]):
        for key in self.bools:
            if self.bools[key][1] in model:
                self.bools[key] = (True, self.bools[key][1])
            else:
                self.bools[key] = (False, self.bools[key][1])

        def substring_tokens(i: int, j: int) -> str:
            return ' '.join(self.word_tokens[i:j+1])

        def print_derivation_helper(nonterminal: NonTerminal, i: int, j: int, indent: str):
            if i > j:
                return

            if self.bools[nonterminal.value + ',' + str(i) + ',' + str(j)][0] == False:
                return

            print(indent + nonterminal.value + ' generates ' + substring_tokens(i, j))

            for rule in self.rules:
                if (
                    rule.type == 'SINGULAR'
                    and rule.nonterminal.value == nonterminal.value
                    and i == j
                    and rule.terminal.value == self.word_tokens[i]
                ):
                    print(indent + '- ' + nonterminal.value + ' -> ' + rule.terminal.value)
                    return

                elif rule.type == 'DOUBLE' and rule.nonterminal.value == nonterminal.value:
                    for k in range(i, j):
                        left_key = rule.nonterminal2.value + ',' + str(i) + ',' + str(k)
                        right_key = rule.nonterminal3.value + ',' + str(k + 1) + ',' + str(j)

                        if self.bools[left_key][0] == True and self.bools[right_key][0] == True:
                            print(indent + '- ' + nonterminal.value + ' -> ' + rule.nonterminal2.value + ' ' + rule.nonterminal3.value)
                            print_derivation_helper(rule.nonterminal2, i, k, indent + '- ')
                            print_derivation_helper(rule.nonterminal3, k + 1, j, indent + '- ')
                            return

        print_derivation_helper(self.startingSymbol, 0, len(self.word_tokens) - 1, '- ')
     

G = parse_grammar_file_to_cnf("src/text/big_grammar.txt")
print_grammar(G)
CFG_2_SAT(G, "function id ( ) : Char begin id := konšt_int ; end")